import "./globals.css";
import Navbar from "./components/navbar";
import ScrollToTopButton from "./components/ScrollToTopButton";

export const metadata = {
  title: "SunSolar",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/letter-s.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <section>
          <nav>
            <Navbar />
          </nav>
          {children}
          <ScrollToTopButton />
        </section>
      </body>
    </html>
  );
}
